apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-hello-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andrewatef21/devops-project.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
