apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello
  namespace: devops
  labels:
    app: java-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-hello
  template:
    metadata:
      labels:
        app: java-hello
    spec:
      containers:
      - name: java-hello
        image: docker.io/andrewatef/java-hello:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 10
