apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: docker.io/andrewatef/java-hello
    newTag: latest
